version: '3'
services:
  eureka:
    build: ./eureka-server
    ports:
      - "80:8761"
      - "8761:8761"
    networks:
      - spring
  zuul:
    build: ./zuul-server
    ports:
      - "8080:8762"
      - "8762:8762"
    networks:
      - spring
    depends_on:
      - eureka
    links:
      - eureka
    environment:
      eureka.client.serviceUrl.defaultZone: http://eureka:8761/eureka/

  user:
    build: ./user-service
    ports:
      - "0:80"
    networks:
      - spring
    depends_on:
      - eureka
    links:
      - eureka
      - redis-user
    environment:
      eureka.client.serviceUrl.defaultZone: http://eureka:8761/eureka/

  stock:
    build: ./stock-service
    ports:
      - "0:80"
    networks:
      - spring
    depends_on:
      - eureka
    links:
      - eureka
      - redis-stock
    environment:
      eureka.client.serviceUrl.defaultZone: http://eureka:8761/eureka/

  redis-user:
    image: "redis:alpine"
    command: [ "redis-server", "--protected-mode", "no", "--appendonly", "yes"]
    volumes:
      - /data
    ports:
     - "6379:6379"
    networks:
      - spring
    
  redis-stock:
    image: "redis:alpine"
    command: [ "redis-server", "--protected-mode", "no", "--appendonly", "yes", "--port", "6380"  ]
    volumes:
      - /data
    ports:
     - "6380:6380"
    networks:
      - spring

  payment:
    build: ./payment-service
    ports:
      - "0:80"
    networks:
      - spring
    depends_on:
      - eureka
    links:
      - eureka
      - redis-payment
    environment:
      eureka.client.serviceUrl.defaultZone: http://eureka:8761/eureka/

  redis-payment:
    image: "redis:alpine"
    command: [ "redis-server", "--protected-mode", "no", "--appendonly", "yes", "--port", "6381"  ]
    volumes:
      - /data
    ports:
     - "6381:6381"
    networks:
      - spring

  order:
    build: ./order-service
    ports:
      - "0:80"
    networks:
      - spring
    depends_on:
      - eureka
    links:
      - eureka
      - redis-order
    environment:
      eureka.client.serviceUrl.defaultZone: http://eureka:8761/eureka/

  redis-order:
    image: "redis:alpine"
    command: [ "redis-server", "--protected-mode", "no", "--appendonly", "yes", "--port", "6382"  ]
    volumes:
      - /data
    ports:
     - "6382:6382"
    networks:
      - spring

networks:
  spring:
    external: true