version: '3'
services:
  eureka:
    build: ./eureka-server
    ports:
      - "80:8761"
      - "8761:8761"
    networks:
      - spring
  zuul:
    build: ./zuul-server
    ports:
      - "8080:8762"
      - "8762:8762"
    networks:
      - spring
    depends_on:
      - eureka
    links:
      - eureka
      - user
    environment:
      eureka.client.serviceUrl.defaultZone: http://eureka:8761/eureka/
  user:
    build: ./user-service
    ports:
      - "7200:80"
    networks:
      - spring
    depends_on:
      - eureka
    links:
      - eureka
    environment:
      eureka.client.serviceUrl.defaultZone: http://eureka:8761/eureka/




networks:
  spring:
    external: true