spring:
  application:
    name: zuul-server

server:
  port: 8762

zuul:
  routes:
    user:
      path: /users/**
      serviceId: user-service
      stripPrefix: false
    stock:
      path: /stock/**
      serviceId: stock-service
      stripPrefix: false
    order:
      path: /orders/**
      serviceId: order-service
      stripPrefix: false
    payment:
      path: /payment/**
      serviceId: payment-service
      stripPrefix: false

management:
  endpoints:
    web:
      exposure:
        include: info, health, routes
  security:
    enabled: false


eureka:
  client:
    registerWithEureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true