spring:
  application:
    name: zuul-server

server:
  port: 8762

zuul:
  routes:
    user:
      path: /user/**
      serviceId: user-service
#    stock:
#      path: /stock/**
#      serviceId: stock-service

eureka:
  client:
    registerWithEureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true