server:
  port: 0

spring:
  application:
    name: user-service

  rabbitmq:
    host: 127.0.0.1
    port: 5672

  cloud:
    stream:
      bindings:
        output:
          destination: users-in
        input:
          consumer:
            partitioned: true
          destination: users-out
          group: users
      rabbit:
        bindings:
          output:
            producer:
              exchangeType: direct
              routingKeyExpression: '"#"'

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/