server:
  port: ${PORT:80}

spring:
  application:
    name: order-service

  rabbitmq:
    host: 127.0.0.1
    port: 5672

  cloud:
    stream:
      bindings:
        output:
          destination: users-in
        input:
          consumer:
            partitioned: true
          destination: users-out
          group: users
      rabbit:
        bindings:
          output:
            producer:
              exchangeType: fanout
#              routingKeyExpression: '"#"'

  redis-order:
    host: 127.0.0.1
    port: 6382

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI/eureka}
  instance:
    preferIpAddress: true
    instanceId: ${spring.application.name}:${server.port}:${spring.application.instance_id:${random.value}}

ribbon:
  eureka:
    enabled: true