server:
  port: ${PORT:0}

spring:
  application:
    name: order-service

  rabbitmq:
    host: 127.0.0.1
    port: 5672

  cloud:
    stream:
      bindings:
        output:
          destination: users-in
        input:
          consumer:
            partitioned: true
          destination: users-out
          group: users
      rabbit:
        bindings:
          output:
            producer:
              exchangeType: fanout
#              routingKeyExpression: '"#"'

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true

ribbon:
  eureka:
    enabled: true