spring:
  application:
    name: eureka-server

server:
  port: 8761

eureka:
  client:
    registerWithEureka: false
    fetch-registry: false

#logging:
#  level:
#    com:
#      netflix:
#        eureka: OFF
#        discovery: OFF